#if UNITY_EDITOR

internal static class RosalinaGeneratorConstants
{
    /// <summary>
    /// Gets the generated code header text.
    /// </summary>
    public static readonly string GeneratedCodeHeader = @$"//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Rosalina Code Generator tool.
//     Version: {RosalinaConstants.Version}
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

";
}

#endif