#if UNITY_EDITOR
using System.IO;

/// <summary>
/// Describes a generation result.
/// </summary>
internal class RosalinaGenerationResult
{
    /// <summary>
    /// Gets the generated code header text.
    /// </summary>
    public static readonly string GeneratedCodeHeader = @$"//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Rosalina Code Generator tool.
//     Version: {RosalinaConstants.Version}
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

";

    /// <summary>
    /// Gets the generated code.
    /// </summary>
    public string Code { get; }

    /// <summary>
    /// Creates a new <see cref="RosalinaGenerationResult"/> instance.
    /// </summary>
    /// <param name="code">Generated code.</param>
    /// <param name="includeHeader">Boolean value that indicates if the Rosalina header should be included in code generation result.</param>
    public RosalinaGenerationResult(string code, bool includeHeader = true)
    {
        Code = includeHeader ? GeneratedCodeHeader + code : code;
    }

    /// <summary>
    /// Saves the result to the output path.
    /// </summary>
    /// <param name="outputFilePath">Output file path.</param>
    public void Save(string outputFilePath)
    {
        if (!string.IsNullOrEmpty(outputFilePath))
        {
            File.WriteAllText(outputFilePath, Code);
        }
    }
}
#endif