#if UNITY_EDITOR
using System.IO;

internal static class RosalinaGenerator
{
    public const string RosalinaFolderName = "Rosalina";
    public const string RosalinaGeneratedCodeFolderName = "AutoGenerated";

    /// <summary>
    /// Creates the auto generated code file path based on the given output file name.
    /// </summary>
    /// <param name="outputFileName">Output file name.</param>
    /// <returns>Auto generated file path.</returns>
    public static string BuildAutoGeneratedFilePath(string outputFileName)
    {
        string autogeneratedFolder = Path.Combine("Assets", RosalinaFolderName, RosalinaGeneratedCodeFolderName);

        if (!Directory.Exists(autogeneratedFolder))
        {
            Directory.CreateDirectory(autogeneratedFolder);
        }

        return Path.Combine(autogeneratedFolder, outputFileName);
    }

    /// <summary>
    /// Generates a C# script containing the bindings of the given UI document.
    /// </summary>
    /// <param name="document">UI Document.</param>
    /// <param name="outputFileName">C# script output file.</param>
    /// <returns>Rosalina generation result.</returns>
    public static RosalinaGenerationResult GenerateBindings(UIDocumentAsset document, string outputFileName)
    {
        return new RosalinaBindingsGenerator().Generate(document, outputFileName);
    }

    /// <summary>
    /// Geneartes a C# script for the UI logic.
    /// </summary>
    /// <param name="document">UI Document asset information.</param>
    /// <param name="outputFileName">Output file name.</param>
    /// <returns>Rosalina generation result.</returns>
    public static RosalinaGenerationResult GenerateScript(UIDocumentAsset document, string outputFileName)
    {
        return new RosalinaScriptGenerator().Generate(document, outputFileName);
    }

    /// <summary>
    /// Deletes the given generated file.
    /// </summary>
    /// <param name="generatedFilePath">Generated file path.</param>
    /// <remarks>
    /// Prior to version 1.3.0, the UXML bindings were generated next to the .uxml document.
    /// In newer versions, documents are generated in Assets/Rosalina/AutoGenerated.
    /// This method is used in bindings generator to delete the previous generated files.
    /// In the future, this method will be deleted.
    /// </remarks>
    public static void DeleteGeneartedFile(string generatedFilePath)
    {
        if (File.Exists(generatedFilePath))
        {
            File.Delete(generatedFilePath);
        }
    }
}
#endif